# Generated by Django 4.2.20 on 2025-04-02 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qnas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qna',
            old_name='author',
            new_name='writer',
        ),
    ]
